version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.13.4
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: ${env:DB_TYPE}
            host: ${env:DB_HOST_NAME}
            port: '5432'
            database: ${env:DB_NAME}
            ssl: true
            user: ${env:DB_USER_NAME}
            password: ${env:DB_PASSWORD}
            migrations: true
